### PR TITLE
Fix runtime error and incorrect analytics in neighborhood view

### LINKED ISSUE #1884: [v2]Bug: Runtime Error and Incorrect Analytics in js/screens/neighborhood.js
## Description
Two bugs in `js/screens/neighborhood.js`  affect UI stability and analytics accuracy.

### 1. Invalid Vue Binding Causes Runtime Error
**Location:** Line 70

Image

When using v-bind, Vue evaluates error-action as a JavaScript expression (error - action), causing ReferenceError since these variables don't exist.
By Adding single quotes around 'error-action' to make it a string literal instead of a JavaScript expression.

### 2. Wrong Analytics Message 
**Location:** Line 645

Image

The joinActivity() function logs "logoff" instead of "join_activity", corrupting analytics by recording all activity joins as user logouts.
By Replacing "logoff" with "join_activity" in the stats.trace() call to correctly track activity join events.

### PR DESCRIPTION
**Pull request by Laxmi01345**
## Description
Fixed two critical issues in the neighborhood view that caused runtime errors and incorrect analytics tracking.

## Changes
- **Line 70**: Fixed Vue binding syntax error `:id="error-action"` → `:id="'error-action'"`
- **Line 645**: Corrected analytics event `"logoff"` → `"join_activity"`

## Issues Fixed
1. **Runtime Error**: Vue was treating `error-action` as a JavaScript expression, causing `ReferenceError: error is not defined` in the console
2. **Incorrect Analytics**: Wrong event name was being logged when users joined shared activities, making analytics data misleading

## Impact
- ✅ Eliminates console errors in neighborhood view
- ✅ Ensures accurate analytics for activity join events
- ✅ Improves debugging and user behavior tracking

Fixed #1884

### CODE REVIEW

File: js/screens/neighborhood.js [hunk 1]
```diff
@@ -642,7 +642,7 @@ const Neighborhood = {
 
 		//prettier-ignore
 		joinActivity(activity, sharedId) {
-			sugarizer.modules.stats.trace("neighborhood_view", "click", "logoff");
+			sugarizer.modules.stats.trace("neighborhood_view", "click", "join_activity");
```
Comment (llaske) [inline js/screens/neighborhood.js]: The trace should just be removed, the following lines do the stats trace.

Comment (Laxmi01345) [reply js/screens/neighborhood.js]: Yes, I have removed it.

**Comment by llaske** [comment]
Nice. Thanks.
